### ISSUE TITLE
not working  pip install git+https://github.com/KiyonoKara/Discord-Build-Info-PY.git#egg=discord_build_info_py

### ISSUE THREAD

**Issue by vst212** [skidghoul/BongoTokenGenerator#6]
pip install git+https://github.com/KiyonoKara/Discord-Build-Info-PY.git#egg=discord_build_info_py

the ljnk is mot work

**Comment by skidghoul** [comment]
don't use this tool, lol.

**Comment by vst212** [comment]
import requests, time, colorama, threading, user_agent, random, string, json, base64, discord_build_info_py, re
Then how to hanlde the thinfgs in calling the building info?

thanks
